// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lygiefterwdolsrvkogm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Z2llZnRlcndkb2xzcnZrb2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODc0NTYsImV4cCI6MjA1OTI2MzQ1Nn0.REdkCn0YvFcOGG4-JrvrjU7ZNifrvYfn5Rm0pT3WTEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);