// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulbzmogzyexqcjwlftnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYnptb2d6eWV4cWNqd2xmdG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTY0NjAsImV4cCI6MjA2MDA3MjQ2MH0.eqg-_eMIBN9dIzcycouqL1Egkjm5LOFxVD4JHeDU8bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);